### ISSUE TITLE
Add a Navbar

### ISSUE THREAD

**Issue by MahirHamiAbrar** [shu-vro/RODE-Solver#8]
Create a Navbar and move the user-login and user-profile from the sidebar to the Navbar.

**Comment by shu-vro** [comment]
this will hamper the mobile view, as too many icons would be in there. we already have sidebar button and topbar button at the `navbar`. in case you didn't find the navbar, move all the way top. you will find those buttons

**Comment by shu-vro** [comment]
however, the bottom login button does create a problem for long mobile devices. so, quite a valid issue.

**Comment by MahirHamiAbrar** [comment]
> this will hamper the mobile view, as too many icons would be in there. we already have sidebar button and topbar button at the `navbar`. in case you didn't find the navbar, move all the way top. you will find those buttons

I would recommend adding both mobile view and desktop view. Desktop view will have a navbar but the mobile view will have a hamburger menu.

**Comment by shu-vro** [comment]
![localhost_3000_ode](https://github.com/shu-vro/RODE-Solver/assets/72239897/10622580-45e3-405d-b5c5-c9543177195e)

Something like this? @MahirHamiAbrar

**Comment by MahirHamiAbrar** [comment]
Yes. But considering the size of phone screens, the `input field` and the `send button` should be placed at the bottom. It's more user friendly this way.

**Comment by shu-vro** [comment]
the problem of placing the input to the bottom is the custom keyboard will hide the input field. so goes for the send button

**Comment by MahirHamiAbrar** [comment]
> the problem of placing the input to the bottom is the custom keyboard will hide the input field. so goes for the send button


Well, the Input field and and the send button should slide up when the custom keyboard will be toggled.
